// <auto-generated />
using Hedgehogs.Persistance.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Hedgehogs.MVC.Migrations
{
    [DbContext(typeof(HedgehogsContext))]
    [Migration("20230604160956_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Hedgehogs.Domain.POCO.Hedgehog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("PictureUrl")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<double>("Radius")
                        .HasColumnType("float");

                    b.Property<int>("SpikeCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Hedgehog", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "i float.",
                            Name = "Miguel",
                            PictureUrl = "https://i.imgur.com/oZMaKdl.png",
                            Radius = 7.6100000000000003,
                            SpikeCount = 4200
                        },
                        new
                        {
                            Id = 2,
                            Description = "Wanted for multiple war crimes in Serbia during the 90s",
                            Name = "Lalo",
                            PictureUrl = "https://i.imgur.com/AljAtSn.jpeg",
                            Radius = 10.0,
                            SpikeCount = 9999
                        },
                        new
                        {
                            Id = 3,
                            Description = "henlo fren i smol, i also love commiting tax fraud on my free time",
                            Name = "Juan",
                            PictureUrl = "https://i.imgur.com/vmz0s3z.jpeg",
                            Radius = 3.1400000000000001,
                            SpikeCount = 3142
                        },
                        new
                        {
                            Id = 4,
                            Description = "Should i add you to my menu? Human is my second favourite meal.",
                            Name = "Antonio",
                            PictureUrl = "https://i.imgur.com/gC7ruMc.jpeg",
                            Radius = 20.0,
                            SpikeCount = 5023
                        },
                        new
                        {
                            Id = 5,
                            Description = "Gotta Go Fast",
                            Name = "Sonic",
                            PictureUrl = "https://i.imgur.com/yqsMMuh.png",
                            Radius = 50.0,
                            SpikeCount = 3
                        },
                        new
                        {
                            Id = 6,
                            Description = "I share wisdom with puny mortals. The sky is blue, Miguel Floats, If you are Bosnian avoid Lalo At all costs and you may not want to cross Antonio in General... There were more of us until he arrived.. Not even Pablo could escape him.",
                            Name = "José",
                            PictureUrl = "https://i.imgur.com/PKqN5gl.jpeg",
                            Radius = 2.0,
                            SpikeCount = 2239
                        },
                        new
                        {
                            Id = 7,
                            Description = "heh? José and wisdom? nice one. He has lost his mind after that Pablo incident and thinks he is an immortal being or something.Anyways listen to me carefully bud, there's only one true wisdom:you either a smart fella or a fart smella.",
                            Name = "Franco",
                            PictureUrl = "https://i.imgur.com/4HeZJTE.jpeg",
                            Radius = 7.7000000000000002,
                            SpikeCount = 6053
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
